- name: create ec2 instance and create route53
  hosts: local
  connection: local
  become: yes
  vars:
    ami_id: ami-0220d79f3f480ecf5
    sg_id: sg-09cddc7470b03f555
    zone_id: "Z0509026150WVAAHWU7IF"
    domain_name: "daws89s.fun"
    instances:
    - mongodb
    # - redis
    # - mysql
    # - rabbitmq
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      instance_type: t3.micro
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      tags:
        Name: "{{ item }}"
    loop: "{{ instances }}"
    register: ec2_output

  - name: print ec2 output
    ansible.builtin.debug:
      msg: "{{ ec2_output }}"

  - name: print public ip address
    ansible.builtin.debug:
      msg: "{{ item.instances[0].public_ip_address }}"
    loop: "{{ ec2_output.results }}"

  - name: print private ip address
    ansible.builtin.debug:
      msg: "{{ item.instances[0].private_ip_address }}"
    loop: "{{ ec2_output.results }}"
  # create route 53 record
  - name: create route 53 record
    amazon.aws.route53:
      state: present
      zone: "{{ domain_name }}"
      record: "{{ item.item }}.{{ domain_name }}"
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      overwrite: true
    loop: "{{ ec2_output.results }}"
  # we are creating one record with public only for frontend
  - name: create route53 record for frontend
    amazon.aws.route53:
      state: present
      zone: "{{ domain_name }}"
      record: "{{ domain_name }}" # daws86s.fun
      type: A
      ttl: 1
      value: "{{ item.instances[0].public_ip_address }}"
      overwrite: true
    when: item.item == "frontend"
    loop: "{{ ec2_output.results }}"