- name: create system user
  ansible.builtin.user:
    name: roboshop
    comment: roboshop system user
    shell: /sbin/nologin
    system: true
    home: /app

- name: remove app directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: create app directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: remove appliaction
  ansible.builtin.file:
    path: /tmp/{{ component }}.zip
    state: absent

- name: downloading {{ component }} application
  ansible.builtin.get_url:
    url: https://roboshop-artifacts.s3.amazonaws.com/{{ component }}-v3.zip
    dest: /tmp/{{ component }}.zip

- name: unarchive {{ component }} application
  ansible.builtin.unarchive:
    src: /tmp/{{ component }}.zip
    dest: /app
    remote_src: yes