- name: install maven
  ansible.builtin.package: 
    name: "{{ item }}"
    state: present
  loop:
  - maven
  - mysql 
- name: install mvn package
  ansible.builtin.command: mvn clean package
  args:
      chdir: /app
- name: move jar file
  ansible.builtin.command: mv target/{{ component }}-{{ version }}.jar {{ component }}.jar 
  args:
    chdir: /app